# Project Context
- **Tech Stack**: React 18, TypeScript, Webpack 5, Emotion (@emotion/styled), @imspdr/ui

# Coding Conventions & Architecture

## 1. Component Structure
- **Directories**: Store components in `src/components/[PascalCaseName]`.
- **Separation of Concerns**:
  - Logic and JSX go in [index.tsx](cci:7://file:///home/konglsh/Documents/kospi200/src/components/Sidebar/index.tsx:0:0-0:0).
  - Styles **MUST** go in [styled.ts](cci:7://file:///home/konglsh/Documents/kospi200/src/components/Sidebar/styled.ts:0:0-0:0) in the same directory.
  - Do not use inline styles unless dynamic (e.g., animation values).

## 2. Styling & Theming
- **Library**: Use `@emotion/styled`.
- **Layout**: Use `Stack` from `@imspdr/ui` for flexbox layouts. **DO NOT** use inline styles or `div` with flex styles.
- **Design Tokens**: 
  - ALWAYS use CSS variables from the `@imspdr/ui` design system for colors.
  - Example: `var(--imspdr-background-bg1)`, `var(--imspdr-foreground-fg1)`, `var(--imspdr-primary-main)`.
  - Avoid hardcoded hex colors to ensure Dark/Light mode compatibility.
- **Responsiveness**:
  - Mobile breakpoint: `768px`.
  - **CRITICAL**: For hover effects, wrap styles in `@media (hover: hover) { ... }`.
    - *Reasoning*: Prevents "sticky" hover states on mobile devices where tap simulates hover.

## 3. Core Libraries
- **UI Types**: Use `Typography` from `@imspdr/ui`. Supported variants: `title`, `body`, `caption`. DO NOT use `label`.
- **Icons**: Use `react-icons/hi` (HeroIcons) or `react-icons/md` as the primary icon set.
- **Routing**: Use `react-router-dom`.
- **Feedback**:  
  - **MUST** use `useToast` from `@imspdr/ui`. Destructure `showToast` and pass a simple string message (e.g., `showToast("Message")`).
  - **DO NOT** use `window.alert` or `console.log` for production code. Use `Toast` or proper error handling instead.
  - **MUST** use `useModal` from `@imspdr/ui`. Destructure `openModal` and `closeModal`. `openModal` takes `(content, options)`. Options include `title` and `footer`.
- **Language**:
  - **MUST** use Korean (Hangul) for all user-facing hardcoded texts (UI labels, toast messages, etc.).

## 4. Feature implementation Rules
- **Sidebar**:
  - Must support a "folded" state.
  - On Mobile (`<= 768px`), clicking an item inside the sidebar MUST auto-fold the sidebar.
- **Data Fetching**:
  - Data is primarily read from static JSON files generated by the crawler. 
  - Handle loading states gracefully.

## 5. Build & Deployment
- **Webpack**:
  - The project uses a custom Webpack config handling Module Federation (exposure of `App`).
  - `publicPath` must be handled dynamically for GitHub Pages deployment.